name: Test building the project in different environments

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os:
          - { image: "ubuntu:20.04", dockerfile: "Dockerfile_DEBIAN" }
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Skip direct build for cross-compilation
        run: echo "Skipping direct build as this is a cross-compilation project."
